export const host = "https://chat-app-aeqj.onrender.com";
export const registerRoute = `${host}/api/auth/register`;
export const loginRoute = `${host}/api/auth/login`
export const setAvatarRoute = `${host}/api/auth/setAvatar`
export const allUsersRoute= `${host}/api/auth/allUsers`
export const sendMsgRoute =  `${host}/api/messages/addmsg`
export const getAllMessagesRoute =  `${host}/api/messages/getmsg`
export const logoutRoute = `${host}/api/auth/logout`;
export const googleAuthRoute = `${host}/api/auth/google`;
export const checkUserNameRoute = `${host}/api/auth/checkusername`;
export const authenticationRoute = `${host}/api/auth/authenticate`;
export const userDataRoute = `${host}/api/auth/get-user-data`;
export const updateUsernameRoute = `${host}/api/auth/update-username`;
